In [2]:
import cv2
import mediapipe as mp
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.layers import Dense,Conv2D,Activation,Flatten,MaxPool2D,Dropout,BatchNormalization
from sklearn.model_selection import train_test_split
import os
import numpy as np

os.chdir("//home//divs//Documents//Vedeo//")
print(os.getcwd())

2023-07-16 21:02:43.606683: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-16 21:02:43.818992: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-16 21:02:43.858413: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/divs/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-07-16 21:02:43

/home/divs/Documents/Vedeo


In [3]:
df=pd.read_csv("sign_mnist_train.csv")
df1=pd.DataFrame(df)

y_train=df1.values[:,:1]
x_train=df1.values[:,1:]

x_train_new=[]

for i in range(len(x_train)):
    image=x_train[i]
    image=image.reshape(28,28)
    x_train_new.append(image)
x_train_new=np.array(x_train_new)
y_train_new=np.array(y_train)
print(x_train_new)

[[[107 118 127 ... 170 170 169]
  [111 121 129 ... 171 171 170]
  [113 123 131 ... 171 171 171]
  ...
  [142 150 159 ... 202 201 200]
  [142 151 160 ... 204 203 202]
  [142 151 160 ... 204 203 202]]

 [[155 157 156 ... 138  92 108]
  [158 159 159 ... 142 116 143]
  [161 161 161 ... 147 125 140]
  ...
  [162 159 145 ...  91 101  94]
  [153 139 115 ...  97  95 120]
  [135 116  95 ... 103 135 149]]

 [[187 188 188 ...  66  77  83]
  [188 189 189 ...  73  73  71]
  [190 190 190 ...  74  68  61]
  ...
  [212 198 175 ... 195 193 192]
  [202 179 152 ... 195 194 193]
  [198 166 132 ... 195 194 195]]

 ...

 [[174 174 174 ... 160 158 156]
  [178 178 177 ... 162 160 158]
  [181 180 180 ... 164 162 161]
  ...
  [215 216 216 ... 201 199 198]
  [216 217 217 ... 201 200 198]
  [217 217 217 ... 202 200 200]]

 [[177 181 184 ... 181 179 177]
  [179 182 185 ... 183 181 179]
  [181 184 187 ... 185 183 182]
  ...
  [129 132 134 ...  94 102  70]
  [131 134 132 ...  78 100  86]
  [136 135 135 ...  64  87  

In [ ]:
cap=cv2.VideoCapture(0)
mpHands= mp.solutions.hands
hands=mpHands.Hands()
mpDraw=mp.solutions.drawing_utils

In [5]:
while True:
    success,image =cap.read()
    imageRGB =cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    results=hands.process(imageRGB)
    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id,lm in enumerate(handLms.landmark):
                h,w,c =image.shape
                cx,cy =int(lm.x*w),int(lm.y*w)
                if id==8:
                    cv2.circle(image, (cx,cy),25,(255,0,255),cv2.FILLED)
            mpDraw.draw_landmarks(image,handLms,mpHands.HAND_CONNECTIONS)
            cv2.imshow("Output",image)
            cv2.waitKey(1)

error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
